### PR TITLE
Change default value of `plot`

### LINKED ISSUE #9: Use `last_plot()` as default `plot`
Hi! Great :package: !

I think setting `last_plot()` as the default value for `plot` in `view_cvd()`,  `cvd_grid()` and `edit_colors()` could make life easier for interactive use.

### PR DESCRIPTION
**Pull request by eliocamp**
Adds `last_plot()` to default value of `plot`. 

Closes #9

### CODE REVIEW

**Comment by clauswilke** [comment]
I committed some changes to the package to make sure it builds on Travis. Could you rebase/merge to  see if your PR passes the checks? I assume  `last_plot()` needs a `ggplot2::` in front or an appropriate @importFrom statement in the roxygen block.

**Comment by eliocamp** [comment]
I'm not good at dependencies and all that, but I believe that since `ggplot2` is listed in "depends", it's not needed. But I added just in case. `devtools::check()` passes on my machine :)

**Comment by clauswilke** [comment]
Yes, you're right. I should probably change that. In any case, the travis build passed, so I'm merging.

**Comment by clauswilke** [comment]
Thanks!

**Pull request merged**
