### PR TITLE
added color palette selector (customize palette)

### PR DESCRIPTION
**Pull request by wckdouglas**
I implemented new buttons to pick color and add to a color list, undo the pick and clear the color list. The color list will be shown as palette_plot on a new tab and a *R* code line will be generated for simple copy-and-paste purpose.

example

### CODE REVIEW

**Review by clauswilke — COMMENTED** [review]
Thanks, this looks good in principle.

A couple of minor issues regarding coding style:
- Please put a space before and after each comparison, assignment, etc. (i.e., around '=', '!=', '<-', etc.). You have done this in many cases but not fully consistently.

- Please make sure there is always a space after each comma. This applies in particular to the generated color list (line 197).

**Comment by clauswilke** [comment]
One more thing, more an idea than a requirement for merging at this time: It would be great if one could click on the colors in the palette plot to set that color in the color picker. With that, though, the unpick function would have to remove the currently selected color, not the last color that was picked.

**Comment by wckdouglas** [comment]
So turns out it is not too hard to implement targeted-color-removal. A minor problem now is that it is silently ignoring duplicated color selections. Ideally, a error/warning message seems to make more sense.

**Comment by clauswilke** [comment]
I made some additional improvements, including making the palette colors clickable. It's quite nice now I think.

**Comment by wckdouglas** [comment]
This does look much better! 

Found a bug on allowing empty color selection, and is fixed in my new pull request
empty_color_bug

**Pull request merged**
